/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String prefix = "abcdefghijklmnopqrstuvwxyz";
        for (int i = 0; i < 12; i++) {
            prefix = prefix + prefix;
        }
        List<String> data = new ArrayList<String>(); 
        for (int i = 0; i < 1000000; i++) {
            if (i == 0) {
                data.add(prefix + " #" + i);
            } else {
                data.add(data.get(i - 1) + " " + "prefix #" + i);
            }
            if (i % 10 == 0) {
                System.out.println(i);
//                System.out.println(data.get(i));
            }
        }
        System.out.println(new App().getGreeting());
    }
}
